version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_express_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - '8000:8000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - '5434:5434'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  node_modules:
  postgres_data:
