version: '3'
services:
  web:
    build: .
    command: make run
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - nginx
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
  redis:
    # Add this Redis service
    image: "redis:alpine"
    ports:
      - "6379:6379"
