WORKER_CREATION_QUEUE = "create_worker_queue"

WORKER_CREATION_EVENT = "Worker_Creation"
WORKER_RUNNING_STATUS = "RUNNING"
WORKER_COMPLETED_STATUS = "COMPLETED"
WORKER_WAITING_FOR_PACKETS_STATUS = "WAITING_FOR_PACKETS"

JOB_STATUS_COMPLETE = "COMPLETED"

OUTPUT_FILE_PATH = "~/job_files/:jobId/output_data/"
